"""initial_tables

Revision ID: 72a7ffa0a4fb
Revises: 
Create Date: 2026-05-05 22:37:06.618339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72a7ffa0a4fb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('etudiant', 'encadreur', 'jury', 'admin', name='roleenum'), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('encadreurs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('specialites', sa.Text(), nullable=True),
    sa.Column('grade', sa.String(length=50), nullable=True),
    sa.Column('charge_actuelle', sa.Integer(), nullable=True),
    sa.Column('max_etudiants', sa.Integer(), nullable=True),
    sa.Column('disponible', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('etudiants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('numero_etudiant', sa.String(length=50), nullable=True),
    sa.Column('filiere', sa.String(length=100), nullable=True),
    sa.Column('niveau', sa.String(length=20), nullable=True),
    sa.Column('annee_inscription', sa.Integer(), nullable=True),
    sa.Column('competences', sa.Text(), nullable=True),
    sa.Column('centres_interet', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_etudiant'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('membres_jury',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('specialites', sa.Text(), nullable=True),
    sa.Column('grade', sa.String(length=50), nullable=True),
    sa.Column('disponible', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('sujets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('etudiant_id', sa.Integer(), nullable=True),
    sa.Column('titre', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('domaine', sa.String(length=100), nullable=True),
    sa.Column('statut', sa.Enum('propose', 'en_evaluation', 'valide', 'rejete', name='statutsujet'), nullable=True),
    sa.Column('score_faisabilite', sa.Float(), nullable=True),
    sa.Column('score_similarite', sa.Float(), nullable=True),
    sa.Column('commentaire_validation', sa.Text(), nullable=True),
    sa.Column('valide_par', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['etudiant_id'], ['etudiants.id'], ),
    sa.ForeignKeyConstraint(['valide_par'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('memoires',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('etudiant_id', sa.Integer(), nullable=True),
    sa.Column('sujet_id', sa.Integer(), nullable=True),
    sa.Column('encadreur_id', sa.Integer(), nullable=True),
    sa.Column('titre_final', sa.String(length=500), nullable=True),
    sa.Column('statut', sa.Enum('en_cours', 'en_attente', 'en_correction', 'valide', 'refuse', 'soutenu', name='statutmemoire'), nullable=True),
    sa.Column('score_plagiat', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['encadreur_id'], ['encadreurs.id'], ),
    sa.ForeignKeyConstraint(['etudiant_id'], ['etudiants.id'], ),
    sa.ForeignKeyConstraint(['sujet_id'], ['sujets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('etudiant_id')
    )
    op.create_table('affectations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('etudiant_id', sa.Integer(), nullable=True),
    sa.Column('encadreur_id', sa.Integer(), nullable=True),
    sa.Column('memoire_id', sa.Integer(), nullable=True),
    sa.Column('date_affectation', sa.DateTime(), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['encadreur_id'], ['encadreurs.id'], ),
    sa.ForeignKeyConstraint(['etudiant_id'], ['etudiants.id'], ),
    sa.ForeignKeyConstraint(['memoire_id'], ['memoires.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('etudiant_id')
    )
    op.create_table('archives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('memoire_id', sa.Integer(), nullable=True),
    sa.Column('titre', sa.String(length=500), nullable=True),
    sa.Column('auteur_nom', sa.String(length=200), nullable=True),
    sa.Column('annee_soutenance', sa.Integer(), nullable=True),
    sa.Column('filiere', sa.String(length=100), nullable=True),
    sa.Column('domaine', sa.String(length=100), nullable=True),
    sa.Column('mots_cles', sa.Text(), nullable=True),
    sa.Column('resume', sa.Text(), nullable=True),
    sa.Column('chemin_fichier', sa.String(length=500), nullable=True),
    sa.Column('acces_public', sa.Boolean(), nullable=True),
    sa.Column('archive_le', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['memoire_id'], ['memoires.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('memoire_id')
    )
    op.create_table('soutenances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('memoire_id', sa.Integer(), nullable=True),
    sa.Column('date_soutenance', sa.DateTime(), nullable=True),
    sa.Column('salle', sa.String(length=100), nullable=True),
    sa.Column('statut', sa.Enum('planifiee', 'confirmee', 'reportee', 'terminee', name='statutsoutenance'), nullable=True),
    sa.Column('president_jury_id', sa.Integer(), nullable=True),
    sa.Column('examinateur_id', sa.Integer(), nullable=True),
    sa.Column('note_finale', sa.Float(), nullable=True),
    sa.Column('mention', sa.String(length=50), nullable=True),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['examinateur_id'], ['membres_jury.id'], ),
    sa.ForeignKeyConstraint(['memoire_id'], ['memoires.id'], ),
    sa.ForeignKeyConstraint(['president_jury_id'], ['membres_jury.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('memoire_id')
    )
    op.create_table('versions_memoire',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('memoire_id', sa.Integer(), nullable=True),
    sa.Column('numero_version', sa.Integer(), nullable=False),
    sa.Column('chemin_fichier', sa.String(length=500), nullable=True),
    sa.Column('nom_fichier', sa.String(length=255), nullable=True),
    sa.Column('taille_fichier', sa.Integer(), nullable=True),
    sa.Column('statut', sa.Enum('en_attente', 'en_correction', 'valide', 'refuse', name='statutversion'), nullable=True),
    sa.Column('depose_le', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['memoire_id'], ['memoires.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('commentaires',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('auteur_id', sa.Integer(), nullable=True),
    sa.Column('contenu', sa.Text(), nullable=False),
    sa.Column('section', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['auteur_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['versions_memoire.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('commentaires')
    op.drop_table('versions_memoire')
    op.drop_table('soutenances')
    op.drop_table('archives')
    op.drop_table('affectations')
    op.drop_table('memoires')
    op.drop_table('sujets')
    op.drop_table('membres_jury')
    op.drop_table('etudiants')
    op.drop_table('encadreurs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
