"""setup_memoire_versioning

Revision ID: abe0806c910d
Revises: 72a7ffa0a4fb
Create Date: 2026-05-13 09:55:54.427157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'abe0806c910d'
down_revision: Union[str, None] = '72a7ffa0a4fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memoires', sa.Column('titre', sa.String(length=300), nullable=False))
    op.add_column('memoires', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('memoires', sa.Column('domaine', sa.String(length=100), nullable=True))
    op.add_column('memoires', sa.Column('annee_academique', sa.String(length=10), nullable=True))
    op.add_column('memoires', sa.Column('cree_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('memoires', sa.Column('mis_a_jour_le', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('memoires', 'statut',
               existing_type=postgresql.ENUM('en_cours', 'en_attente', 'en_correction', 'valide', 'refuse', 'soutenu', name='statutmemoire'),
               nullable=False)
    op.alter_column('memoires', 'etudiant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('memoires_etudiant_id_key', 'memoires', type_='unique')
    op.create_index(op.f('ix_memoires_id'), 'memoires', ['id'], unique=False)
    op.drop_constraint('memoires_encadreur_id_fkey', 'memoires', type_='foreignkey')
    op.drop_constraint('memoires_sujet_id_fkey', 'memoires', type_='foreignkey')
    op.create_foreign_key(None, 'memoires', 'users', ['encadreur_id'], ['id'])
    op.drop_column('memoires', 'score_plagiat')
    op.drop_column('memoires', 'updated_at')
    op.drop_column('memoires', 'sujet_id')
    op.drop_column('memoires', 'titre_final')
    op.drop_column('memoires', 'created_at')
    op.add_column('versions_memoire', sa.Column('nom_fichier_original', sa.String(length=255), nullable=False))
    op.add_column('versions_memoire', sa.Column('nom_fichier_stocke', sa.String(length=255), nullable=False))
    op.add_column('versions_memoire', sa.Column('taille_fichier_ko', sa.Integer(), nullable=True))
    op.add_column('versions_memoire', sa.Column('message_depot', sa.Text(), nullable=True))
    op.add_column('versions_memoire', sa.Column('est_version_courante', sa.Boolean(), nullable=False))
    op.add_column('versions_memoire', sa.Column('depose_par_id', sa.Integer(), nullable=False))
    op.alter_column('versions_memoire', 'memoire_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('versions_memoire', 'chemin_fichier',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.alter_column('versions_memoire', 'depose_le',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_index(op.f('ix_versions_memoire_id'), 'versions_memoire', ['id'], unique=False)
    op.create_foreign_key(None, 'versions_memoire', 'users', ['depose_par_id'], ['id'])
    op.drop_column('versions_memoire', 'nom_fichier')
    op.drop_column('versions_memoire', 'taille_fichier')
    op.drop_column('versions_memoire', 'statut')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('versions_memoire', sa.Column('statut', postgresql.ENUM('en_attente', 'en_correction', 'valide', 'refuse', name='statutversion'), autoincrement=False, nullable=True))
    op.add_column('versions_memoire', sa.Column('taille_fichier', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('versions_memoire', sa.Column('nom_fichier', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'versions_memoire', type_='foreignkey')
    op.drop_index(op.f('ix_versions_memoire_id'), table_name='versions_memoire')
    op.alter_column('versions_memoire', 'depose_le',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('versions_memoire', 'chemin_fichier',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('versions_memoire', 'memoire_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('versions_memoire', 'depose_par_id')
    op.drop_column('versions_memoire', 'est_version_courante')
    op.drop_column('versions_memoire', 'message_depot')
    op.drop_column('versions_memoire', 'taille_fichier_ko')
    op.drop_column('versions_memoire', 'nom_fichier_stocke')
    op.drop_column('versions_memoire', 'nom_fichier_original')
    op.add_column('memoires', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('memoires', sa.Column('titre_final', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('memoires', sa.Column('sujet_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('memoires', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('memoires', sa.Column('score_plagiat', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'memoires', type_='foreignkey')
    op.create_foreign_key('memoires_sujet_id_fkey', 'memoires', 'sujets', ['sujet_id'], ['id'])
    op.create_foreign_key('memoires_encadreur_id_fkey', 'memoires', 'encadreurs', ['encadreur_id'], ['id'])
    op.drop_index(op.f('ix_memoires_id'), table_name='memoires')
    op.create_unique_constraint('memoires_etudiant_id_key', 'memoires', ['etudiant_id'])
    op.alter_column('memoires', 'etudiant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('memoires', 'statut',
               existing_type=postgresql.ENUM('en_cours', 'en_attente', 'en_correction', 'valide', 'refuse', 'soutenu', name='statutmemoire'),
               nullable=True)
    op.drop_column('memoires', 'mis_a_jour_le')
    op.drop_column('memoires', 'cree_le')
    op.drop_column('memoires', 'annee_academique')
    op.drop_column('memoires', 'domaine')
    op.drop_column('memoires', 'description')
    op.drop_column('memoires', 'titre')
    # ### end Alembic commands ###
