"""Migrate all PKs to UUID

Revision ID: ea661d24c3d3
Revises: 42773cad4228
Create Date: 2026-05-13 18:43:13.805480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea661d24c3d3'
down_revision: Union[str, None] = '42773cad4228'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('affectations', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('affectations', 'etudiant_id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('affectations', 'encadreur_id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('affectations', 'memoire_id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.create_index(op.f('ix_affectations_id'), 'affectations', ['id'], unique=False)
    op.alter_column('archives', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('archives', 'memoire_id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.create_index(op.f('ix_archives_id'), 'archives', ['id'], unique=False)
    op.alter_column('commentaires', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('commentaires', 'version_id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('commentaires', 'auteur_id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.create_index(op.f('ix_commentaires_id'), 'commentaires', ['id'], unique=False)
    op.alter_column('encadreurs', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('encadreurs_id_seq'::regclass)"))
    op.alter_column('encadreurs', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('encadreurs', 'charge_actuelle',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=10),
               existing_nullable=True)
    op.alter_column('encadreurs', 'max_etudiants',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=10),
               existing_nullable=True)
    op.create_index(op.f('ix_encadreurs_id'), 'encadreurs', ['id'], unique=False)
    op.alter_column('etudiants', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('etudiants_id_seq'::regclass)"))
    op.alter_column('etudiants', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('etudiants', 'annee_inscription',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=9),
               existing_nullable=True)
    op.create_index(op.f('ix_etudiants_id'), 'etudiants', ['id'], unique=False)
    op.alter_column('membres_jury', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('membres_jury_id_seq'::regclass)"))
    op.alter_column('membres_jury', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.create_index(op.f('ix_membres_jury_id'), 'membres_jury', ['id'], unique=False)
    op.alter_column('memoires', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('memoires_id_seq'::regclass)"))
    op.alter_column('memoires', 'etudiant_id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('memoires', 'encadreur_id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('soutenances', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('soutenances', 'memoire_id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('soutenances', 'president_jury_id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('soutenances', 'examinateur_id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.create_index(op.f('ix_soutenances_id'), 'soutenances', ['id'], unique=False)
    op.alter_column('sujets', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('sujets', 'etudiant_id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('sujets', 'valide_par',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.create_index(op.f('ix_sujets_id'), 'sujets', ['id'], unique=False)
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('users_id_seq'::regclass)"))
    op.alter_column('users', 'otp_code',
               existing_type=sa.VARCHAR(length=6),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.alter_column('versions_memoire', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('versions_memoire', 'memoire_id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('versions_memoire', 'depose_par_id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('versions_memoire', 'depose_par_id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('versions_memoire', 'memoire_id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('versions_memoire', 'id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.alter_column('users', 'otp_code',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=6),
               existing_nullable=True)
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('users_id_seq'::regclass)"))
    op.drop_index(op.f('ix_sujets_id'), table_name='sujets')
    op.alter_column('sujets', 'valide_par',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('sujets', 'etudiant_id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('sujets', 'id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_index(op.f('ix_soutenances_id'), table_name='soutenances')
    op.alter_column('soutenances', 'examinateur_id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('soutenances', 'president_jury_id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('soutenances', 'memoire_id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('soutenances', 'id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('memoires', 'encadreur_id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('memoires', 'etudiant_id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('memoires', 'id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('memoires_id_seq'::regclass)"))
    op.drop_index(op.f('ix_membres_jury_id'), table_name='membres_jury')
    op.alter_column('membres_jury', 'user_id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('membres_jury', 'id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('membres_jury_id_seq'::regclass)"))
    op.drop_index(op.f('ix_etudiants_id'), table_name='etudiants')
    op.alter_column('etudiants', 'annee_inscription',
               existing_type=sa.String(length=9),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('etudiants', 'user_id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('etudiants', 'id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('etudiants_id_seq'::regclass)"))
    op.drop_index(op.f('ix_encadreurs_id'), table_name='encadreurs')
    op.alter_column('encadreurs', 'max_etudiants',
               existing_type=sa.String(length=10),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('encadreurs', 'charge_actuelle',
               existing_type=sa.String(length=10),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('encadreurs', 'user_id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('encadreurs', 'id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('encadreurs_id_seq'::regclass)"))
    op.drop_index(op.f('ix_commentaires_id'), table_name='commentaires')
    op.alter_column('commentaires', 'auteur_id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('commentaires', 'version_id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('commentaires', 'id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_index(op.f('ix_archives_id'), table_name='archives')
    op.alter_column('archives', 'memoire_id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('archives', 'id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_index(op.f('ix_affectations_id'), table_name='affectations')
    op.alter_column('affectations', 'memoire_id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('affectations', 'encadreur_id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('affectations', 'etudiant_id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('affectations', 'id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
